### ISSUE TITLE
`SyntaxError: Unexpected token {` on SSR (Next.js)

### ISSUE THREAD

**Issue by isBatak** [juggle/resize-observer#91]
**Describe the bug**
[react-three-fiber](https://github.com/react-spring/react-three-fiber) is using this lib and I'm trying to use it with next.js.  
I'm getting this error 
```
Unexpected token {
./node_modules/@juggle/resize-observer/lib/ResizeObserver.js:1
(function (exports, require, module, __filename, __dirname) { import { ResizeObserverController } from './ResizeObserverController';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (./node_modules/react-three-fiber/web.cjs.js:17:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
``` 
which you can see in the code sandbox example below.

**To Reproduce**
Here is code sandbox reproduction https://codesandbox.io/s/resize-observer-issue-98jp2

**Expected behavior**
Should work without error.

**Frameworks/Libraries used**
Next.js, React, react-three-fiber

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: chrome
 - Version: 79.0.3945.88

**Comment by TremayneChrist** [comment]
Hi @isBatak, yeah this is the same issue which is causing #82. There's a [pre-release](https://github.com/juggle/resize-observer/releases/tag/v3.0.0-0) version which fixes this. I've updated your sample as a test https://codesandbox.io/s/resize-observer-issue-55mch
